import type { PrayerTimesMap } from '@/types/database';

interface VaktijaEuDayData {
  fajr: string;
  sunrise: string;
  dhuhr: string;
  asr: string;
  maghrib: string;
  isha: string;
}

interface VaktijaEuApiResponse {
  data: {
    months: Record<string, {
      days: Record<string, VaktijaEuDayData>;
    }>;
  };
}

const PRAYER_KEYS: (keyof PrayerTimesMap)[] = ['fajr', 'sunrise', 'dhuhr', 'asr', 'maghrib', 'isha'];

function toHHMM(hhmmss: string): string {
  const [h, m] = hhmmss.split(':');
  return `${h.padStart(2, '0')}:${m.padStart(2, '0')}`;
}

export async function fetchVaktijaEu(locationSlug: string): Promise<PrayerTimesMap> {
  const res = await fetch(`https://api.vaktija.eu/v3/locations/slug/${locationSlug}`, {
    next: { revalidate: 3600 },
  });

  if (!res.ok) {
    throw new Error(`Vaktija.eu API error: ${res.status}`);
  }

  const data: VaktijaEuApiResponse = await res.json();
  const now = new Date();
  const month = String(now.getMonth() + 1);
  const day = String(now.getDate());

  const dayData = data.data.months[month]?.days[day];
  if (!dayData) {
    throw new Error('No prayer times found for today');
  }

  const times = {} as PrayerTimesMap;
  for (const key of PRAYER_KEYS) {
    times[key] = toHHMM(dayData[key]);
  }

  return times;
}

// --- Location Data ---

export interface VaktijaEuLocation {
  slug: string;
  name: string;
}

export interface VaktijaEuCountry {
  code: string;
  name: string;
  locations: VaktijaEuLocation[];
}

export const VAKTIJA_EU_COUNTRIES: VaktijaEuCountry[] = [
  { code: "AT", name: "Austria", locations: [
    { slug: "amstetten", name: "Amstetten" },
    { slug: "bludenz", name: "Bludenz" },
    { slug: "braunau-am-inn", name: "Braunau am Inn" },
    { slug: "bregenz", name: "Bregenz" },
    { slug: "dornbirn", name: "Dornbirn" },
    { slug: "eisenstadt", name: "Eisenstadt" },
    { slug: "enns", name: "Enns" },
    { slug: "feldkirch", name: "Feldkirch" },
    { slug: "gaenserndorf", name: "Gänserndorf" },
    { slug: "gerasdorf", name: "Gerasdorf" },
    { slug: "gmuend", name: "Gmünd" },
    { slug: "gmunden", name: "Gmunden" },
    { slug: "graz", name: "Graz" },
    { slug: "hall-in-tirol", name: "Hall in Tirol" },
    { slug: "hollabrunn", name: "Hollabrunn" },
    { slug: "horn", name: "Horn" },
    { slug: "innsbruck", name: "Innsbruck" },
    { slug: "judenburg", name: "Judenburg" },
    { slug: "kapfenberg", name: "Kapfenberg" },
    { slug: "krems", name: "Krems" },
    { slug: "kufstein", name: "Kufstein" },
    { slug: "landeck", name: "Landeck" },
    { slug: "leoben", name: "Leoben" },
    { slug: "liezen", name: "Liezen" },
    { slug: "linz", name: "Linz" },
    { slug: "melk", name: "Melk" },
    { slug: "mistelbach", name: "Mistelbach" },
    { slug: "mittersill", name: "Mittersill" },
    { slug: "m\u00f6dling", name: "Mödling" },
    { slug: "rankweil", name: "Rankweil" },
    { slug: "reutte", name: "Reutte" },
    { slug: "salzburg", name: "Salzburg" },
    { slug: "spittal", name: "Spittal an der Drau" },
    { slug: "st-johann", name: "St. Johann im Pongau" },
    { slug: "st-poelten", name: "St. Pölten" },
    { slug: "steyr", name: "Steyr" },
    { slug: "tulln", name: "Tulln" },
    { slug: "villach", name: "Villach" },
    { slug: "voecklabruck", name: "Vöcklabruck" },
    { slug: "wels", name: "Wels" },
    { slug: "wien", name: "Wien" },
    { slug: "wolfsberg", name: "Wolfsberg" },
    { slug: "ypps-an-der-donau", name: "Ypps an der Donau" },
    { slug: "zeltweg", name: "Zeltweg" },
    { slug: "zwettl", name: "Zwettl" },
  ] },
  { code: "BE", name: "Belgium", locations: [
    { slug: "aalst", name: "Aalst" },
    { slug: "antwerpen", name: "Antwerpen" },
    { slug: "bouillon", name: "Bouillon" },
    { slug: "brugge", name: "Brugge" },
    { slug: "brussels", name: "Brussels" },
    { slug: "charleroi", name: "Charleroi" },
    { slug: "dinant", name: "Dinant" },
    { slug: "eupen", name: "Eupen" },
    { slug: "genk", name: "Genk" },
    { slug: "gent", name: "Gent" },
    { slug: "hasselt", name: "Hasselt" },
    { slug: "hoogstraten", name: "Hoogstraten" },
    { slug: "houffalize", name: "Houffalize" },
    { slug: "kortrijk", name: "Kortrijk" },
    { slug: "luttich", name: "Luttich" },
    { slug: "malmedy", name: "Malmedy" },
    { slug: "mons", name: "Mons" },
    { slug: "namur", name: "Namur" },
    { slug: "ostende", name: "Ostende" },
    { slug: "peruwelz", name: "Péruwelz" },
    { slug: "poperinge", name: "Poperinge" },
    { slug: "roeselare", name: "Roeselare" },
    { slug: "ronse", name: "Ronse" },
    { slug: "sint-niklaas", name: "Sint-Niklaas" },
    { slug: "tournai", name: "Tournai" },
    { slug: "turnhout", name: "Turnhout" },
    { slug: "veurne", name: "Veurne" },
    { slug: "virton", name: "Virton" },
    { slug: "waregem", name: "Waregem" },
  ] },
  { code: "BA", name: "Bosnia & Herzegovina", locations: [
    { slug: "banja-luka", name: "Banja Luka" },
    { slug: "banovici", name: "Banovići" },
    { slug: "bihac", name: "Bihać" },
    { slug: "bijeljina", name: "Bijeljina" },
    { slug: "bileca", name: "Bileća" },
    { slug: "bosanska-dubica", name: "Bosanska Dubica" },
    { slug: "bosanska-gradiska", name: "Bosanska Gradiška" },
    { slug: "bosanska-krupa", name: "Bosanska Krupa" },
    { slug: "bosanski-brod", name: "Bosanski Brod" },
    { slug: "bosanski-novi", name: "Bosanski Novi" },
    { slug: "bosanski-petrovac", name: "Bosanski Petrovac" },
    { slug: "bosanski-samac", name: "Bosanski Šamac" },
    { slug: "bosansko-grahovo", name: "Bosansko Grahovo" },
    { slug: "bratunac", name: "Bratunac" },
    { slug: "brcko", name: "Brčko" },
    { slug: "breza", name: "Breza" },
    { slug: "bugojno", name: "Bugojno" },
    { slug: "busovaca", name: "Busovača" },
    { slug: "buzim", name: "Bužim" },
    { slug: "cajnice", name: "Čajniče" },
    { slug: "capljina", name: "Čapljina" },
    { slug: "cazin", name: "Cazin" },
    { slug: "celic", name: "Čelič" },
    { slug: "celinac", name: "Čelinac" },
    { slug: "citluk", name: "Čitluk" },
    { slug: "derventa", name: "Derventa" },
    { slug: "doboj", name: "Doboj" },
    { slug: "donji-vakuf", name: "Donji Vakuf" },
    { slug: "drvar", name: "Drvar" },
    { slug: "foca", name: "Foča" },
    { slug: "fojnica", name: "Fojnica" },
    { slug: "gacko", name: "Gacko" },
    { slug: "glamoc", name: "Glamoč" },
    { slug: "gorazde", name: "Goražde" },
    { slug: "gornji-vakuf", name: "Gornji Vakuf" },
    { slug: "gracanica", name: "Gračanica" },
    { slug: "gradacac", name: "Gradačac" },
    { slug: "grude", name: "Grude" },
    { slug: "hadzici", name: "Hadžići" },
    { slug: "han-pijesak", name: "Han-Pijesak" },
    { slug: "hlivno", name: "Hlivno" },
    { slug: "ilijas", name: "Ilijaš" },
    { slug: "jablanica", name: "Jablanica" },
    { slug: "jajce", name: "Jajce" },
    { slug: "kakanj", name: "Kakanj" },
    { slug: "kalesija", name: "Kalesija" },
    { slug: "kalinovik", name: "Kalinovik" },
    { slug: "kiseljak", name: "Kiseljak" },
    { slug: "kladanj", name: "Kladanj" },
    { slug: "kljuc", name: "Ključ" },
    { slug: "konjic", name: "Konjic" },
    { slug: "kotor-varos", name: "Kotor-Varoš" },
    { slug: "kresevo", name: "Kreševo" },
    { slug: "kupres", name: "Kupres" },
    { slug: "laktasi", name: "Laktaši" },
    { slug: "ljubinje", name: "Ljubinje" },
    { slug: "ljubuski", name: "Ljubuški" },
    { slug: "lopare", name: "Lopare" },
    { slug: "lukavac", name: "Lukavac" },
    { slug: "maglaj", name: "Maglaj" },
    { slug: "modrica", name: "Modriča" },
    { slug: "mostar", name: "Mostar" },
    { slug: "mrkonjic-grad", name: "Mrkonjić-Grad" },
    { slug: "neum", name: "Neum" },
    { slug: "nevesinje", name: "Nevesinje" },
    { slug: "novi-travnik", name: "Novi Travnik" },
    { slug: "odzak", name: "Odžak" },
    { slug: "olovo", name: "Olovo" },
    { slug: "orasje", name: "Orašje" },
    { slug: "pale", name: "Pale" },
    { slug: "posusje", name: "Posušje" },
    { slug: "prijedor", name: "Prijedor" },
    { slug: "prnjavor", name: "Prnjavor" },
    { slug: "prozor", name: "Prozor" },
    { slug: "rogatica", name: "Rogatica" },
    { slug: "rudo", name: "Rudo" },
    { slug: "sanski-most", name: "Sanski Most" },
    { slug: "sarajevo", name: "Sarajevo" },
    { slug: "sekovici", name: "Šekovići" },
    { slug: "sipovo", name: "Šipovo" },
    { slug: "siroki-brijeg", name: "Široki Brijeg" },
    { slug: "skender-vakuf", name: "Skender-Vakuf" },
    { slug: "sokolac", name: "Sokolac" },
    { slug: "srbac", name: "Srbac" },
    { slug: "srebrenica", name: "Srebrenica" },
    { slug: "srebrenik", name: "Srebrenik" },
    { slug: "stolac", name: "Stolac" },
    { slug: "tesanj", name: "Tešanj" },
    { slug: "teslic", name: "Teslić" },
    { slug: "tomislavgrad", name: "Tomislavgrad" },
    { slug: "travnik", name: "Travnik" },
    { slug: "trebinje", name: "Trebinje" },
    { slug: "trnovo", name: "Trnovo" },
    { slug: "tuzla", name: "Tuzla" },
    { slug: "ugljevik", name: "Ugljevik" },
    { slug: "ustikolina", name: "Ustikolina" },
    { slug: "vares", name: "Vareš" },
    { slug: "velika-kladusa", name: "Velika Kladuša" },
    { slug: "visegrad", name: "Višegrad" },
    { slug: "visoko", name: "Visoko" },
    { slug: "vitez", name: "Vitez" },
    { slug: "vlasenica", name: "Vlasenica" },
    { slug: "zavidovici", name: "Zavidovići" },
    { slug: "zenica", name: "Zenica" },
    { slug: "zepa", name: "Žepa" },
    { slug: "zepce", name: "Žepče" },
    { slug: "zivinice", name: "Živinice" },
    { slug: "zvornik", name: "Zvornik" },
  ] },
  { code: "HR", name: "Croatia", locations: [
    { slug: "dubrovnik", name: "Dubrovnik" },
    { slug: "gunja", name: "Gunja" },
    { slug: "karlovac", name: "Karlovac" },
    { slug: "labin", name: "Labin" },
    { slug: "osijek", name: "Osijek" },
    { slug: "porec", name: "Poreč" },
    { slug: "pula", name: "Pula" },
    { slug: "rijeka", name: "Rijeka" },
    { slug: "sisak", name: "Sisak" },
    { slug: "slavonski-brod", name: "Slavonski Brod" },
    { slug: "split", name: "Split" },
    { slug: "umag", name: "Umag" },
    { slug: "varazdin", name: "Varaždin" },
    { slug: "vinkovci", name: "Vinkovci" },
    { slug: "zadar", name: "Zadar" },
    { slug: "zagreb", name: "Zagreb" },
  ] },
  { code: "DK", name: "Denmark", locations: [
    { slug: "aarhus", name: "Aarhus" },
    { slug: "abenraa", name: "Åbenraa" },
    { slug: "alborg", name: "Ålborg" },
    { slug: "brande", name: "Brande" },
    { slug: "esbjerg", name: "Esbjerg" },
    { slug: "flensburg", name: "Flensburg" },
    { slug: "fredericia", name: "Fredericia" },
    { slug: "frederikshavn", name: "Frederikshavn" },
    { slug: "horsens", name: "Horsens" },
    { slug: "kolding", name: "Kolding" },
    { slug: "kopenhagen", name: "Kopenhagen" },
    { slug: "naestved", name: "Næstved" },
    { slug: "nakskov", name: "Nakskov" },
    { slug: "odense", name: "Odense" },
    { slug: "randers", name: "Randers" },
    { slug: "slagelse", name: "Slagelse" },
    { slug: "sonderborg", name: "Sønderborg" },
    { slug: "svendborg", name: "Svendborg" },
    { slug: "thisted", name: "Thisted" },
    { slug: "tonder", name: "Tønder" },
    { slug: "vejle", name: "Vejle" },
  ] },
  { code: "FR", name: "France", locations: [
    { slug: "angers", name: "Angers" },
    { slug: "annecy", name: "Annecy" },
    { slug: "avignon", name: "Avignon" },
    { slug: "besancon", name: "Besançon" },
    { slug: "bethune", name: "Béthune" },
    { slug: "bordeaux", name: "Bordeaux" },
    { slug: "brest", name: "Brest" },
    { slug: "caen", name: "Caen" },
    { slug: "clermont-ferrand", name: "Clermont-Ferrand" },
    { slug: "cluses", name: "Cluses" },
    { slug: "dijon", name: "Dijon" },
    { slug: "grenoble", name: "Grenoble" },
    { slug: "le-mans", name: "Le Mans" },
    { slug: "lens", name: "Lens" },
    { slug: "lille", name: "Lille" },
    { slug: "lyon", name: "Lyon" },
    { slug: "marseille", name: "Marseille" },
    { slug: "metz", name: "Metz" },
    { slug: "montpellier", name: "Montpellier" },
    { slug: "mulhouse", name: "Mulhouse" },
    { slug: "nancy", name: "Nancy" },
    { slug: "nantes", name: "Nantes" },
    { slug: "nice", name: "Nice" },
    { slug: "orleans", name: "Orléans" },
    { slug: "paris", name: "Paris" },
    { slug: "reims", name: "Reims" },
    { slug: "rennes", name: "Rennes" },
    { slug: "rouen", name: "Rouen" },
    { slug: "saint-etienne", name: "Saint-Étienne" },
    { slug: "sochaux", name: "Sochaux" },
    { slug: "strasbourg", name: "Strasbourg" },
    { slug: "thonon-les-bains", name: "Thonon-les-Bains" },
    { slug: "toulon", name: "Toulon" },
    { slug: "toulouse", name: "Toulouse" },
    { slug: "tours", name: "Tours" },
    { slug: "valenciennes", name: "Valenciennes" },
  ] },
  { code: "DE", name: "Germany", locations: [
    { slug: "aachen", name: "Aachen" },
    { slug: "ahlen", name: "Ahlen" },
    { slug: "augsburg", name: "Augsburg" },
    { slug: "balingen", name: "Balingen" },
    { slug: "belzig", name: "Belzig" },
    { slug: "berlin", name: "Berlin" },
    { slug: "bielefeld", name: "Bielefeld" },
    { slug: "bochum", name: "Bochum" },
    { slug: "bonn", name: "Bonn" },
    { slug: "brandenburg", name: "Brandenburg" },
    { slug: "braunschweig", name: "Braunschweig" },
    { slug: "bremen", name: "Bremen" },
    { slug: "bremerhaven", name: "Bremerhaven" },
    { slug: "calw", name: "Calw" },
    { slug: "castrop-rauxel", name: "Castrop-Rauxel" },
    { slug: "darmstadt", name: "Darmstadt" },
    { slug: "dortmund", name: "Dortmund" },
    { slug: "dresden", name: "Dresden" },
    { slug: "duisburg", name: "Duisburg" },
    { slug: "duesseldorf", name: "Düsseldorf" },
    { slug: "eningen", name: "Eningen" },
    { slug: "essen", name: "Essen" },
    { slug: "frankfurt", name: "Frankfurt" },
    { slug: "freiburg", name: "Freiburg" },
    { slug: "gaggenau", name: "Gaggenau" },
    { slug: "hagen", name: "Hagen" },
    { slug: "halle", name: "Halle" },
    { slug: "hamburg", name: "Hamburg" },
    { slug: "hamm", name: "Hamm" },
    { slug: "hanau", name: "Hanau" },
    { slug: "hannover", name: "Hannover" },
    { slug: "heilbronn", name: "Heilbronn" },
    { slug: "ingolstadt", name: "Ingolstadt" },
    { slug: "kamenz", name: "Kamenz" },
    { slug: "kamp-lintfort", name: "Kamp-Lintfort" },
    { slug: "karlsruhe", name: "Karlsruhe" },
    { slug: "kassel", name: "Kassel" },
    { slug: "kiel", name: "Kiel" },
    { slug: "kirchheim-teck", name: "Kirchheim Teck" },
    { slug: "koblenz", name: "Koblenz" },
    { slug: "koeln", name: "Köln" },
    { slug: "leipzig", name: "Leipzig" },
    { slug: "loehne", name: "Löhne" },
    { slug: "ludwigsburg", name: "Ludwigsburg" },
    { slug: "mainz", name: "Mainz" },
    { slug: "mannheim", name: "Mannheim" },
    { slug: "muehlheim", name: "Mühlheim" },
    { slug: "muenchen", name: "München" },
    { slug: "nuernberg", name: "Nürnberg" },
    { slug: "oberhausen", name: "Oberhausen" },
    { slug: "offenbach", name: "Offenbach" },
    { slug: "osnabrueck", name: "Osnabrück" },
    { slug: "paderborn", name: "Paderborn" },
    { slug: "penzberg", name: "Penzberg" },
    { slug: "pfalzgrafenweiler", name: "Pfalzgrafenweiler" },
    { slug: "philippsburg", name: "Philippsburg" },
    { slug: "ravensburg", name: "Ravensburg" },
    { slug: "regensburg", name: "Regensburg" },
    { slug: "reutlingen", name: "Reutlingen" },
    { slug: "rosenheim", name: "Rosenheim" },
    { slug: "saarbruecken", name: "Saarbrücken" },
    { slug: "schwaebisch-gmuend", name: "Schwäbisch Gmünd" },
    { slug: "siegen", name: "Siegen" },
    { slug: "sindelfingen", name: "Sindelfingen" },
    { slug: "stuttgart", name: "Stuttgart" },
    { slug: "tuttlingen", name: "Tuttlingen" },
    { slug: "uhingen", name: "Uhingen" },
    { slug: "ulm", name: "Ulm" },
    { slug: "velbert", name: "Velbert" },
    { slug: "wiesbaden", name: "Wiesbaden" },
    { slug: "witten", name: "Witten" },
    { slug: "wuppertal", name: "Wuppertal" },
    { slug: "wuerzburg", name: "Würzburg" },
  ] },
  { code: "IT", name: "Italy", locations: [
    { slug: "agrigento", name: "Agrigento" },
    { slug: "alessandria", name: "Alessandria" },
    { slug: "ancona", name: "Ancona" },
    { slug: "bari", name: "Bari" },
    { slug: "benevento", name: "Benevento" },
    { slug: "bergamo", name: "Bergamo" },
    { slug: "biella", name: "Biella" },
    { slug: "bologna", name: "Bologna" },
    { slug: "bolzano", name: "Bolzano" },
    { slug: "brescia", name: "Brescia" },
    { slug: "brindisi", name: "Brindisi" },
    { slug: "cagliari", name: "Cagliari" },
    { slug: "campobasso", name: "Campobasso" },
    { slug: "catania", name: "Catania" },
    { slug: "catanzaro", name: "Catanzaro" },
    { slug: "cosenza", name: "Cosenza" },
    { slug: "costa-volpino", name: "Costa Volpino" },
    { slug: "crotone", name: "Crotone" },
    { slug: "ferrara", name: "Ferrara" },
    { slug: "firenze", name: "Firenze" },
    { slug: "foggia", name: "Foggia" },
    { slug: "frosinone", name: "Frosinone" },
    { slug: "gaglianco", name: "Gaglianco" },
    { slug: "genova", name: "Genova" },
    { slug: "grosseto", name: "Grosseto" },
    { slug: "la-spezia", name: "La Spezia" },
    { slug: "latina", name: "Latina" },
    { slug: "lecce", name: "Lecce" },
    { slug: "marsala", name: "Marsala" },
    { slug: "milano", name: "Milano" },
    { slug: "modena", name: "Modena" },
    { slug: "napoli", name: "Napoli" },
    { slug: "olbia", name: "Olbia" },
    { slug: "oristano", name: "Oristano" },
    { slug: "palermo", name: "Palermo" },
    { slug: "parma", name: "Parma" },
    { slug: "perugia", name: "Perugia" },
    { slug: "pescara", name: "Pescara" },
    { slug: "piacenza", name: "Piacenza" },
    { slug: "pisa", name: "Pisa" },
    { slug: "pordenone", name: "Pordenone" },
    { slug: "potenza", name: "Potenza" },
    { slug: "ravenna", name: "Ravenna" },
    { slug: "reggio-calabria", name: "Reggio Calabria" },
    { slug: "rieti", name: "Rieti" },
    { slug: "rimini", name: "Rimini" },
    { slug: "rogno", name: "Rogno" },
    { slug: "roma", name: "Roma" },
    { slug: "salerno", name: "Salerno" },
    { slug: "sassari", name: "Sassari" },
    { slug: "siena", name: "Siena" },
    { slug: "siracusa", name: "Siracusa" },
    { slug: "taranto", name: "Taranto" },
    { slug: "termoli", name: "Termoli" },
    { slug: "torino", name: "Torino" },
    { slug: "trento", name: "Trento" },
    { slug: "trieste", name: "Trieste" },
    { slug: "udine", name: "Udine" },
    { slug: "venezia", name: "Venezia" },
    { slug: "verona", name: "Verona" },
    { slug: "vicenza", name: "Vicenza" },
    { slug: "viterbo", name: "Viterbo" },
  ] },
  { code: "LI", name: "Liechtenstein", locations: [
    { slug: "vaduz", name: "Vaduz" },
  ] },
  { code: "LU", name: "Luxembourg", locations: [
    { slug: "luxembourg", name: "Luxembourg" },
  ] },
  { code: "ME", name: "Montenegro", locations: [
    { slug: "andrijevica", name: "Andrijevica" },
    { slug: "bar", name: "Bar" },
    { slug: "berane", name: "Berane" },
    { slug: "bijelo-polje", name: "Bijelo Polje" },
    { slug: "budva", name: "Budva" },
    { slug: "cetinje", name: "Cetinje" },
    { slug: "danilovgrad", name: "Danilovgrad" },
    { slug: "herceg-novi", name: "Herceg Novi" },
    { slug: "kolasin", name: "Kolašin" },
    { slug: "kotor", name: "Kotor" },
    { slug: "niksic", name: "Nikšić" },
    { slug: "plav", name: "Plav" },
    { slug: "pljevlja", name: "Pljevlja" },
    { slug: "pluzine", name: "Plužine" },
    { slug: "podgorica", name: "Podgorica" },
    { slug: "rozaje", name: "Rožaje" },
    { slug: "savnik", name: "Šavnik" },
    { slug: "sutomore", name: "Sutomore" },
    { slug: "tivat", name: "Tivat" },
    { slug: "ulcinj", name: "Ulcinj" },
    { slug: "zabljak", name: "Žabljak" },
  ] },
  { code: "NL", name: "Netherlands", locations: [
    { slug: "almere", name: "Almere" },
    { slug: "amsterdam", name: "Amsterdam" },
    { slug: "apeldoorn", name: "Apeldoorn" },
    { slug: "arnhem", name: "Arnhem" },
    { slug: "den-haag", name: "Den Haag" },
    { slug: "den-bosch", name: "Den-Bosch" },
    { slug: "eindhoven", name: "Eindhoven" },
    { slug: "enschede", name: "Enschede" },
    { slug: "groningen", name: "Groningen" },
    { slug: "nijmegen", name: "Nijmegen" },
    { slug: "roermond", name: "Roermond" },
    { slug: "rotterdam", name: "Rotterdam" },
    { slug: "utrecht", name: "Utrecht" },
  ] },
  { code: "NO", name: "Norway", locations: [
    { slug: "alesund", name: "Alesund" },
    { slug: "arendal", name: "Arendal" },
    { slug: "bergen", name: "Bergen" },
    { slug: "drammen", name: "Drammen" },
    { slug: "elverum", name: "Elverum" },
    { slug: "gjovik", name: "Gjøvik" },
    { slug: "haugesund", name: "Haugesund" },
    { slug: "horten", name: "Horten" },
    { slug: "kristiansand", name: "Kristiansand" },
    { slug: "lillehammer", name: "Lillehammer" },
    { slug: "mandal", name: "Mandal" },
    { slug: "oslo", name: "Oslo" },
    { slug: "ostfold", name: "Østfold" },
    { slug: "stavanger", name: "Stavanger" },
    { slug: "trondheim", name: "Trondheim" },
    { slug: "vestfold", name: "Vestfold" },
  ] },
  { code: "RS", name: "Serbia", locations: [
    { slug: "beograd", name: "Beograd" },
    { slug: "nis", name: "Niš" },
    { slug: "nova-varos", name: "Nova Varoš" },
    { slug: "novi-pazar", name: "Novi Pazar" },
    { slug: "novi-sad", name: "Novi Sad" },
    { slug: "presevo", name: "Preševo" },
    { slug: "priboj", name: "Priboj" },
    { slug: "prijepolje", name: "Prijepolje" },
    { slug: "sjenica", name: "Sjenica" },
    { slug: "subotica", name: "Subotica" },
    { slug: "tutin", name: "Tutin" },
  ] },
  { code: "SI", name: "Slovenia", locations: [
    { slug: "celje", name: "Celje" },
    { slug: "jesenice", name: "Jesenice" },
    { slug: "koper", name: "Koper" },
    { slug: "ljubljana", name: "Ljubljana" },
    { slug: "maribor", name: "Maribor" },
  ] },
  { code: "SE", name: "Sweden", locations: [
    { slug: "boras", name: "Borås" },
    { slug: "gislaved", name: "Gislaved" },
    { slug: "goeteborg", name: "Göteborg" },
    { slug: "halmstad", name: "Halmstad" },
    { slug: "helsingborg", name: "Helsingborg" },
    { slug: "joenkoeping", name: "Jönköping" },
    { slug: "kalmar", name: "Kalmar" },
    { slug: "landskrona", name: "Landskrona" },
    { slug: "linkoeping", name: "Linköping" },
    { slug: "malmoe", name: "Malmö" },
    { slug: "norrkoeping", name: "Norrköping" },
    { slug: "oerebro", name: "Örebro" },
    { slug: "oskarshamn", name: "Oskarshamn" },
    { slug: "stockholm", name: "Stockholm" },
    { slug: "trollhaettan", name: "Trollhättan" },
    { slug: "vaesteras", name: "Västerås" },
    { slug: "vaexjoe", name: "Växjö" },
  ] },
  { code: "CH", name: "Switzerland", locations: [
    { slug: "aarau", name: "Aarau" },
    { slug: "appenzell", name: "Appenzell" },
    { slug: "basel", name: "Basel" },
    { slug: "bern", name: "Bern" },
    { slug: "biel", name: "Biel" },
    { slug: "bischofszell", name: "Bischofszell" },
    { slug: "buchs", name: "Buchs" },
    { slug: "chur", name: "Chur" },
    { slug: "genf", name: "Genf" },
    { slug: "heiden", name: "Heiden" },
    { slug: "kreuzlingen", name: "Kreuzlingen" },
    { slug: "luzern", name: "Luzern" },
    { slug: "neuchatel", name: "Neuchâtel" },
    { slug: "ricken", name: "Ricken" },
    { slug: "st-gallen", name: "St. Gallen" },
    { slug: "wattwil", name: "Wattwil" },
    { slug: "yverdon", name: "Yverdon" },
    { slug: "zuerich", name: "Zürich" },
  ] },
];
